image: nodejs

stages:
  - test
  - publish


# lint:
#   stage: test
#   script:
#   - make lint


publish-to-medium:
  stage: publish
  only:
    - master
  before_script:
    - yarn
  script:
    - yarn run publish